# Generated by Django 6.0.1 on 2026-01-09 18:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('insurancecompany', '0001_initial'),
        ('provider', '0001_initial'),
        ('servicesoperators', '0001_initial'),
        ('servicetype', '0001_initial'),
        ('workorderstatus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Work order code')),
                ('description', models.TextField(verbose_name='Service description')),
                ('technical_report', models.TextField(blank=True, verbose_name='Technical report')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='Scheduled date')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished at')),
                ('estimated_time_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Estimated time (minutes)')),
                ('real_time_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Real execution time (minutes)')),
                ('labor_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Labor cost')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='clients.client', verbose_name='Client')),
                ('insurance_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='insurancecompany.insurancecompany', verbose_name='Insurance company')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='provider.provider', verbose_name='Provider')),
                ('service_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='servicesoperators.serviceoperator', verbose_name='Service operator')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='servicetype.servicetype', verbose_name='Service type')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='workorderstatus.workorderstatus', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Work Order',
                'verbose_name_plural': 'Work Orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='workorder_w_code_c02793_idx'), models.Index(fields=['status'], name='workorder_w_status__0e8d4f_idx'), models.Index(fields=['scheduled_date'], name='workorder_w_schedul_a32bf4_idx')],
            },
        ),
    ]
