# Generated by Django 6.0.1 on 2026-01-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0002_workorderevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='actions',
            field=models.TextField(blank=True, verbose_name='Actions taken'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='address',
            field=models.TextField(blank=True, verbose_name='Service address'),
        ),
    ]
