# Generated by Django 5.2.8 on 2026-01-16 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('workorder', '0003_workorder_actions_workorder_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='clients.client', verbose_name='Client'),
        ),
    ]
