# Generated by Django 5.2.8 on 2026-01-16 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
        ('workorder', '0004_alter_workorder_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='provider.provider', verbose_name='Provider'),
        ),
    ]
