# Generated by Django 5.2.8 on 2026-01-16 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicetype', '0002_servicetype_billing_unit_and_more'),
        ('workorder', '0005_alter_workorder_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='servicetype.servicetype', verbose_name='Service type'),
        ),
    ]
