# Generated by Django 5.2.8 on 2026-01-17 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0006_alter_workorder_service_type'),
        ('workorderstatus', '0002_serviceorderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='workorderstatus.serviceorderstatus', verbose_name='Status'),
        ),
    ]
