# Generated by Django 6.0.1 on 2026-01-18 19:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('insurancecompany', '0002_insurancecompany_contact_name'),
        ('provider', '0002_provider_rating_avg_provider_rating_count'),
        ('servicetype', '0003_servicetype_estimated_price'),
        ('workorder', '0008_workorder_evaluation_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='address_city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='address_complement',
            field=models.CharField(blank=True, max_length=120, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='address_neighborhood',
            field=models.CharField(blank=True, max_length=120, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='address_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='N?mero'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='address_state',
            field=models.CharField(blank=True, max_length=60, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='address_street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Rua'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='address_zip',
            field=models.CharField(blank=True, max_length=20, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='address',
            field=models.TextField(blank=True, verbose_name='Endere?o completo'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='clients.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='description',
            field=models.TextField(verbose_name='Descriçao do Serviço'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='estimated_time_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo estimado'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='evaluation_rating',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação (0-5 estrelas)'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Término'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='insurance_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='insurancecompany.insurancecompany', verbose_name='Seguradora'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='provider.provider', verbose_name='Técnico'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='real_time_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo real'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='servicetype.servicetype', verbose_name='Tipo de serviço'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início'),
        ),
    ]
