# Generated by Django 6.0.1 on 2026-01-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0009_workorder_address_city_workorder_address_complement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='closed_on',
            field=models.DateField(blank=True, null=True, verbose_name='Data de encerramento'),
        ),
    ]
