# Generated by Django 6.0.1 on 2026-01-23 03:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_category_dre_group'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='finance_tra_user_id_f69cf8_idx',
            old_name='finance_tra_user_id_5b993e_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='finance_tra_user_id_877912_idx',
            old_name='finance_tra_user_id_2d2484_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='finance_tra_data_ve_ce0010_idx',
            old_name='finance_tra_data_ve_f03a62_idx',
        ),
        migrations.AlterField(
            model_name='account',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Saldo Inicial'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor'),
        ),
    ]
