# Generated by Django 6.0.1 on 2026-01-24 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_rename_finance_tra_user_id_5b993e_idx_finance_tra_user_id_f69cf8_idx_and_more'),
        ('servicetype', '0006_costitem_cost_behavior_costitem_expense_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='expense_type',
            field=models.CharField(blank=True, choices=[('direto', 'Custo Direto'), ('indireto', 'Custo Indireto'), ('fixo', 'Custo Fixo'), ('variavel', 'Custo Variável'), ('administrativo', 'Despesa Administrativa'), ('operacional', 'Despesa Operacional'), ('financeiro', 'Despesa Financeira')], help_text='Classificação da despesa para controle de custos', max_length=20, null=True, verbose_name='Tipo de Despesa'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Marque se esta despesa se repete periodicamente', verbose_name='É Recorrente?'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recurrence_period',
            field=models.CharField(choices=[('unico', 'Único (Não Recorrente)'), ('mensal', 'Mensal'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='unico', max_length=20, verbose_name='Período de Recorrência'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_service_type',
            field=models.ForeignKey(blank=True, help_text='Vincule esta despesa a um tipo de serviço específico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_transactions', to='servicetype.servicetype', verbose_name='Tipo de Serviço Relacionado'),
        ),
    ]
