# Generated by Django 6.0.1 on 2026-01-26 16:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_account_is_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Saldo Inicial'),
        ),
    ]
