# Generated by Django 6.0.1 on 2026-01-27 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_account_saldo_inicial'),
        ('workorder', '0010_workorder_closed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='installment_group_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Grupo de parcelas'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='installment_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero da parcela'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='installment_total',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total de parcelas'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_installment',
            field=models.BooleanField(default=False, verbose_name='Parcela de recebimento'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_origin',
            field=models.CharField(blank=True, choices=[('pix', 'PIX'), ('ted', 'TED'), ('cartao', 'Cartão'), ('boleto', 'Boleto')], max_length=20, null=True, verbose_name='Origem de Pagamento'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('previsto', 'Previsto'), ('realizado', 'Realizado'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], default='previsto', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='work_order',
            field=models.ForeignKey(blank=True, help_text='Vinculo automatico com OS para contas a receber.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_transactions', to='workorder.workorder', verbose_name='Ordem de Servico'),
        ),
    ]
