# Generated by Django 6.0.1 on 2026-01-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_transaction_installment_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_projection',
            field=models.BooleanField(default=False, verbose_name='Previsao de recebimento'),
        ),
    ]
