# Generated by Django 6.0.1 on 2026-01-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_ensure_is_projection_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='boleto_issued_at',
            field=models.DateField(blank=True, null=True, verbose_name='Data de emissao do Boleto'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='boleto_number',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Numero do Boleto'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='invoice_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Dados da NF'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='invoice_issued_at',
            field=models.DateField(blank=True, null=True, verbose_name='Data de emissao da NF'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Numero da NF'),
        ),
    ]
