# Generated by Django 6.0.1 on 2026-01-26 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ'),
        ),
    ]
