# Generated by Django 5.2.8 on 2026-01-17 21:43

from django.db import migrations, models
from django.db.models import Avg, Count


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
        ('workorder', '0008_workorder_evaluation_rating'),
    ]

    def seed_provider_ratings(apps, schema_editor):
        Provider = apps.get_model('provider', 'Provider')
        WorkOrder = apps.get_model('workorder', 'WorkOrder')

        ratings = WorkOrder.objects.filter(
            evaluation_rating__gt=0,
            provider__isnull=False
        ).values('provider').annotate(
            avg=Avg('evaluation_rating'),
            cnt=Count('id')
        )

        rating_map = {item['provider']: (item['avg'] or 0, item['cnt'] or 0) for item in ratings}

        for provider in Provider.objects.all().iterator():
            avg, cnt = rating_map.get(provider.id, (0, 0))
            provider.rating_avg = round(avg or 0, 2)
            provider.rating_count = cnt or 0
            provider.save(update_fields=['rating_avg', 'rating_count'])

    operations = [
        migrations.AddField(
            model_name='provider',
            name='rating_avg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='M?dia de avalia??o'),
        ),
        migrations.AddField(
            model_name='provider',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade de avalia??es'),
        ),
        migrations.RunPython(seed_provider_ratings, migrations.RunPython.noop),
    ]
