# Generated by Django 6.0.1 on 2026-01-09 18:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do serviço')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('ferramentas', models.TextField(blank=True, verbose_name='Descrição')),
                ('duracao_estimada', models.IntegerField(blank=True, default=0, verbose_name='Tempo estimado')),
                ('duracao_media', models.IntegerField(blank=True, default=0, verbose_name='Tempo médio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Tipo de Serviço',
                'verbose_name_plural': 'Tipos de Serviço',
                'ordering': ['name'],
            },
        ),
    ]
