# Generated by Django 6.0.1 on 2026-01-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicetype', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='billing_unit',
            field=models.CharField(choices=[('hora', 'Hora'), ('unidade', 'Unidade'), ('km', 'Quilômetro'), ('dia', 'Dia'), ('visita', 'Visita'), ('m2', 'Metro Quadrado'), ('consulta', 'Consulta'), ('sessao', 'Sessão'), ('servico', 'Serviço Completo'), ('outro', 'Outro')], default='unidade', max_length=20, verbose_name='Unidade de Cobrança'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='default_quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Quantidade padrão de unidades para este serviço', max_digits=10, verbose_name='Quantidade Padrão'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor por unidade (R$)', max_digits=10, verbose_name='Valor Unitário'),
        ),
    ]
