# Generated by Django 6.0.1 on 2026-01-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicetype', '0002_servicetype_billing_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='estimated_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor Estimado (R$)', max_digits=10, verbose_name='Valor Estimado'),
        ),
    ]
