# Generated by Django 5.2.8 on 2026-01-23 02:12

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicetype', '0003_servicetype_estimated_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140, unique=True, verbose_name='Nome do custo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('cost_type', models.CharField(choices=[('direto', 'Direto'), ('indireto', 'Indireto')], default='direto', max_length=20, verbose_name='Tipo de custo')),
                ('billing_unit', models.CharField(choices=[('hora', 'Hora'), ('unidade', 'Unidade'), ('km', 'Quilômetro'), ('dia', 'Dia'), ('visita', 'Visita'), ('m2', 'Metro Quadrado'), ('consulta', 'Consulta'), ('sessao', 'Sessão'), ('servico', 'Serviço Completo'), ('outro', 'Outro')], default='unidade', max_length=20, verbose_name='Unidade de cobrança')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Custo unitário')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Item de Custo',
                'verbose_name_plural': 'Itens de Custo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantidade')),
                ('unit_cost_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor do custo no momento da associação', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Custo unitário congelado')),
                ('is_required', models.BooleanField(default=True, verbose_name='Obrigatório')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_costs', to='servicetype.costitem', verbose_name='Custo')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_costs', to='servicetype.servicetype', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Custo do Serviço',
                'verbose_name_plural': 'Custos dos Serviços',
                'ordering': ['service_type', 'cost_item'],
                'indexes': [models.Index(fields=['service_type'], name='servicetype_service_f5f80a_idx'), models.Index(fields=['cost_item'], name='servicetype_cost_it_c1df97_idx')],
                'constraints': [models.UniqueConstraint(fields=('service_type', 'cost_item'), name='unique_service_cost_per_pair')],
            },
        ),
    ]
