# Generated by Django 5.2.8 on 2026-01-23 02:42

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicetype', '0004_costitem_servicecost'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140, unique=True, verbose_name='Nome do perfil fiscal')),
                ('iss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='ISS (%)')),
                ('federal_taxes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Impostos Federais (%)')),
                ('financial_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Taxas Financeiras (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Perfil Fiscal',
                'verbose_name_plural': 'Perfis Fiscais',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='servicetype',
            name='margin_minimum',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Margem Mínima (%)'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='margin_target',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Margem Alvo (%)'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='volume_baseline',
            field=models.PositiveIntegerField(default=1, verbose_name='Volume Base'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='tax_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicetype.taxprofile', verbose_name='Perfil Fiscal'),
        ),
    ]
