# Generated by Django 5.2.8 on 2026-01-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicetype', '0005_taxprofile_servicetype_margin_minimum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costitem',
            name='cost_behavior',
            field=models.CharField(choices=[('fixo', 'Fixo'), ('variavel', 'Variável'), ('mistura', 'Misto')], default='fixo', max_length=10, verbose_name='Comportamento de custo'),
        ),
        migrations.AddField(
            model_name='costitem',
            name='expense_group',
            field=models.CharField(choices=[('operacional', 'Operacional'), ('administrativo', 'Administrativo'), ('imposto', 'Impostos & Taxas'), ('outros', 'Outros')], default='operacional', max_length=20, verbose_name='Grupo de despesa'),
        ),
    ]
