# Generated by Django 6.0.1 on 2026-01-09 19:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workorder', '0001_initial'),
        ('workorderstatus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, verbose_name='Note / observation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
                ('new_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_status_histories', to='workorderstatus.workorderstatus', verbose_name='New status')),
                ('previous_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_status_histories', to='workorderstatus.workorderstatus', verbose_name='Previous status')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='workorder.workorder', verbose_name='Work order')),
            ],
            options={
                'verbose_name': 'Work Order History',
                'verbose_name_plural': 'Work Order Histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['work_order'], name='workorderhi_work_or_60f049_idx'), models.Index(fields=['created_at'], name='workorderhi_created_982154_idx')],
            },
        ),
    ]
