# Generated by Django 5.2.8 on 2026-01-17 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorderhistory', '0001_initial'),
        ('workorderstatus', '0002_serviceorderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderhistory',
            name='new_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_status_histories', to='workorderstatus.serviceorderstatus', verbose_name='New status'),
        ),
        migrations.AlterField(
            model_name='workorderhistory',
            name='previous_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_status_histories', to='workorderstatus.serviceorderstatus', verbose_name='Previous status'),
        ),
    ]
