# Generated by Django 6.0.1 on 2026-01-09 18:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome do status')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Status da Ordem',
                'verbose_name_plural': 'Status das Ordens',
                'ordering': ['order', 'name'],
            },
        ),
    ]
