# Generated by Django 5.2.8 on 2026-01-17 11:51

import uuid
from django.db import migrations, models


def seed_prd_statuses(apps, schema_editor):
    ServiceOrderStatus = apps.get_model('workorderstatus', 'ServiceOrderStatus')
    statuses = [
        # Abertas (OPEN)
        {'group_code': 'OPEN', 'group_name': 'Abertas', 'group_color': 'orange', 'status_code': 'CREATED', 'status_name': 'Criada', 'status_order': 1, 'is_final': False},
        {'group_code': 'OPEN', 'group_name': 'Abertas', 'group_color': 'orange', 'status_code': 'WAITING_SCHEDULING', 'status_name': 'Aguardando agendamento', 'status_order': 2, 'is_final': False},
        {'group_code': 'OPEN', 'group_name': 'Abertas', 'group_color': 'orange', 'status_code': 'SCHEDULED', 'status_name': 'Agendada', 'status_order': 3, 'is_final': False},
        # Em Andamento (IN_PROGRESS)
        {'group_code': 'IN_PROGRESS', 'group_name': 'Em Andamento', 'group_color': 'blue', 'status_code': 'IN_ROUTE', 'status_name': 'Em deslocamento', 'status_order': 4, 'is_final': False},
        {'group_code': 'IN_PROGRESS', 'group_name': 'Em Andamento', 'group_color': 'blue', 'status_code': 'IN_EXECUTION', 'status_name': 'Em execução', 'status_order': 5, 'is_final': False},
        {'group_code': 'IN_PROGRESS', 'group_name': 'Em Andamento', 'group_color': 'blue', 'status_code': 'PAUSED', 'status_name': 'Pausada', 'status_order': 6, 'is_final': False},
        {'group_code': 'IN_PROGRESS', 'group_name': 'Em Andamento', 'group_color': 'blue', 'status_code': 'WAITING_MATERIAL', 'status_name': 'Aguardando material', 'status_order': 7, 'is_final': False},
        # Em Validação (VALIDATION)
        {'group_code': 'VALIDATION', 'group_name': 'Em Validação', 'group_color': 'green', 'status_code': 'WAITING_VALIDATION', 'status_name': 'Aguardando validação', 'status_order': 8, 'is_final': False},
        {'group_code': 'VALIDATION', 'group_name': 'Em Validação', 'group_color': 'green', 'status_code': 'REWORK', 'status_name': 'Retrabalho', 'status_order': 9, 'is_final': False},
        # Finalizadas (CLOSED)
        {'group_code': 'CLOSED', 'group_name': 'Finalizadas', 'group_color': 'gray', 'status_code': 'COMPLETED', 'status_name': 'Concluída', 'status_order': 10, 'is_final': True},
        {'group_code': 'CLOSED', 'group_name': 'Finalizadas', 'group_color': 'gray', 'status_code': 'FINANCIAL_CLOSED', 'status_name': 'Encerrada financeiramente', 'status_order': 11, 'is_final': True},
        {'group_code': 'CLOSED', 'group_name': 'Finalizadas', 'group_color': 'gray', 'status_code': 'CANCELED', 'status_name': 'Cancelada', 'status_order': 12, 'is_final': True},
    ]

    for status in statuses:
        ServiceOrderStatus.objects.get_or_create(
            group_code=status['group_code'],
            status_code=status['status_code'],
            defaults={
                'group_name': status['group_name'],
                'group_color': status['group_color'],
                'status_name': status['status_name'],
                'status_order': status['status_order'],
                'is_final': status['is_final'],
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('workorderstatus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrderStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_code', models.CharField(max_length=30)),
                ('group_name', models.CharField(max_length=50)),
                ('group_color', models.CharField(max_length=10)),
                ('status_code', models.CharField(max_length=50)),
                ('status_name', models.CharField(max_length=100)),
                ('status_order', models.IntegerField(default=0)),
                ('is_final', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Status da OS (Grupo + Status)',
                'verbose_name_plural': 'Status das OS (Grupo + Status)',
                'ordering': ['status_order', 'group_name', 'status_name'],
                'indexes': [models.Index(fields=['group_code'], name='workorderst_group_c_76f79f_idx'), models.Index(fields=['status_code'], name='workorderst_status__d8dd0a_idx'), models.Index(fields=['is_active'], name='workorderst_is_acti_c2a974_idx'), models.Index(fields=['is_final'], name='workorderst_is_fina_bbe8e8_idx')],
                'unique_together': {('group_code', 'status_code')},
            },
        ),
        migrations.RunPython(seed_prd_statuses, migrations.RunPython.noop),
    ]
