# Generated by Django 6.0.1 on 2026-01-09 18:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOperator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Company name')),
                ('trade_name', models.CharField(blank=True, max_length=150, verbose_name='Trade name')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('responsible_name', models.CharField(blank=True, max_length=150, verbose_name='Responsible person')),
                ('responsible_role', models.CharField(blank=True, max_length=100, verbose_name='Responsible role')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Main email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Main phone')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('street', models.CharField(blank=True, max_length=255)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('complement', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Service Operator',
                'verbose_name_plural': 'Service Operators',
                'ordering': ['name'],
            },
        ),
    ]
