# Generated by Django 6.0.1 on 2026-01-09 18:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nome da seguradora')),
                ('trade_name', models.CharField(blank=True, max_length=150, verbose_name='Nome fantasia')),
                ('document', models.CharField(blank=True, max_length=20, verbose_name='CNPJ')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail de contato')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone de contato')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Seguradora',
                'verbose_name_plural': 'Seguradoras',
                'ordering': ['name'],
            },
        ),
    ]
