# Generated by Django 6.0.1 on 2026-01-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurancecompany', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecompany',
            name='contact_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nome de contato'),
        ),
    ]
